name: Build & Deploy
on: 
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14.0
    - run: npm install # npm ci
    - run: npm run build
    - run: npm run package-release
#     - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishExtension@1
#       displayName: "Publish Extension"
#       inputs:
#           connectedServiceName: Marketplace ms-devlabs
#           fileType: vsix
#           vsixFile: "ms-devlabs.estimate-*.vsix"
#           updateTasksVersion: false
